version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: rasa_requests.log

loggers:
  rasa:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

  rasa.core.processor:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

  rasa.core.channels:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

  rasa.nlu.model:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

  rasa.core.nlg.generator:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

  rasa.core.trackers:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

  rasa.core.interpreter:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

root:
  level: DEBUG
  handlers: [console, file_handler]
